name: CI

on:
  push:
    branches: [ master, redo ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    # Use the official vcpkg action with caching
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgGitCommitId: '2024.07.12'
        vcpkgJsonGlob: 'vcpkg.json'

    # Configure CMake
    - name: Configure CMake
      run: |
        cmake -B build -S . `
          -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" `
          -DCMAKE_BUILD_TYPE=Release `
          -DBUILD_TESTS=ON `
          -DVCPKG_TARGET_TRIPLET=x64-windows

    # Build
    - name: Build
      run: cmake --build build --config Release --parallel

    # Run tests
    - name: Run tests
      working-directory: build
      run: ctest --output-on-failure --build-config Release

    # Upload test results on failure
    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          build/Testing/Temporary/LastTest.log
          build/tests/*.exe
